production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
development:
  clients:
    default:
      database: twitifi_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: twitifi_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
