# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5381730c3332e69ffefca7997a54598030c4b55c32a2974e3ec2d1c79e9f8d5c935f5726da7bb8fcd570900865f0cd531ef9948199d938a5234d2d1b11a7189c

test:
  secret_key_base: 14b9c2b8f169d38e0249b0730d70b037200ef8df105f92f91b1c1cc62b15b8b958608ccb031003d586502f5bb26b12874a54a2bb591eb076520db8b03773d276

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
